const menu = [
  {
    id: 1,
    title: 'buttermilk pancakes',
    category: 'breakfast',
    price: 119.99,
    img: './images/item-1.jpeg',
    desc: `A pancake or hotcake is a flat cake, often thin and round, prepared from a starch-based batter. `,
  },
  {
    id: 2,
    title: 'gujrati thali',
    category: 'lunch',
    price: 199.99,
    img: './images/gthali.jpg',
    desc: 'Gujarati thali prepared in Gujarati households has at least three fresh vegetable dishes, one dry dal or some sprouted pulses dish a wet dal, kadhi, kathor, mithai, poori, rotis, steamed rice, chaash and papad'
  },
  {
    id: 3,
    title: 'godzilla milkshake',
    category: 'snacks',
    price: 89.99,
    img: './images/item-3.jpeg',
    desc:'A milkshake is a sweet drink made by blending milk, ice cream, and flavorings or sweeteners such as butterscotch, chocolate syrup, or whole fruit into a thick, sweet, cold mixture.',
  },
  {
    id: 4,
    title: 'coffee',
    category: 'breakfast',
    price: 19.99,
    img: './images/coffee.jpg',
    desc: 'Coffee is a brewed drink prepared from roasted coffee beans, the seeds of berries from certain Coffea species.',
  },
  {
    id: 5,
    title: 'puran poli',
    category: 'lunch',
    price: 69.99,
    img: './images/pp.jpg',
    desc: 'Puran Poli is eaten with a variant of Amti known as Katachi Amti is prepared with the remaining water of Chana Dal used to make Puran.'
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'snacks',
    price: 79.99,
    img: './images/item-6.jpeg',
    desc:'A milkshake is a sweet drink made by blending milk, ice cream, and flavorings or sweeteners such as butterscotch, chocolate syrup, or whole fruit into a thick, sweet, cold mixture.',
  },
  {
    id: 7,
    title: 'poori-bhaji',
    category: 'breakfast',
    price: 89.99,
    img: './images/poori.jpg',
    desc:'Puri bhaji is a dish, originating from the Indian subcontinent, of puri and aloo bhaj. It is a traditional breakfast dish in North India.',
  },
  {
    id: 8,
    title: 'american classic',
    category: 'snacks',
    price: 149.99,
    img: './images/item-8.jpeg',
    desc: ` A hamburger is a sandwich consisting of one or more cooked patties of ground meat, usually beef, placed inside a sliced bread roll or bun. The patty may be pan fried, grilled, smoked.`,
  },

  {
    id: 9,
    title: 'pizza',
    category: 'snacks',
    price: 179.99,
    img: './images/pizza.jpg',
    desc: `Pizza, dish of Italian origin consisting of a flattened disk of bread dough topped with some combination of olive oil, tomato, olives, cheese, and many other ingredients. `,
  },
  {
    id: 10,
    title: 'dosas',
    category: 'breakfast',
    price: 89.99,
    img: './images/dosa.jpg',
    desc: ` A dosa is a thin pancake or crepe, originating from South India, made from a fermented batter predominantly consisting of lentils and rice. `,
  },
  {
    id: 11,
    title: 'idli',
    category: 'breakfast',
    price: 49.99,
    img: './images/idli.jpg',
    desc: `Idli are a type of savoury rice cake, originating from the Indian subcontinent, popular as breakfast foods in Southern India and all over the world. `,
  },
  {
    id: 12,
    title: 'pav-bhaji',
    category: 'snacks',
    price: 99.99,
    img: './images/pav.jpg',
    desc:' Pav bhaji is a popular Indian street food that consists of a spicy mix vegetable mash & soft buns. Usually pav bhaji is served with a generous amount of butter topped along with some fresh chopped onions & lemon juice.',
  },
  {
    id: 13,
    title: 'dal-bati',
    category: 'lunch',
    price: 149.99,
    img: './images/dbt.jpg',
    desc: 'Dal Baati is a popular Rajasthani dish consisting of mainly Uradh Dal (combination of five lentils) and Baati i.e. small wheat bread balls. Baati is dipped in pure ghee and served hot in a traditional earthen pot.',
    },
    {
      id: 14,
      title: 'sabudana-vada',
      category: 'lunch',
      price: 99.99,
      img: './images/sbv.jpg',
      desc: 'Sabudana vada is a popular crisp fried snack made with tapioca pearls, roasted peanuts, boiled potatoes and herbs.',
    },
    {
      id: 15,
      title: 'paneer butter masala',
      category: 'lunch',
      price: 199.99,
      img: './images/pm.jpg',
      desc: 'paneer butter masala is one of the most popular paneer recipes in Indian cuisine. The near perfect combination of spiciness and creaminess of its gravy makes it one of the most popular Indian dishes.',
    },
];
export default menu;
